export const newStudentForm = [
  {
    id: "first_name",
    name: "first_name",
    label: "First Name",
    type: "text",
    colSize: 6,
  },
  {
    id: "last_name",
    name: "last_name",
    label: "Last Name",
    type: "text",
    colSize: 6,
  },
  {
    id: "email",
    name: "email",
    label: "Email",
    type: "email",
    colSize: 12,
    can_be_disabled: false,
  },
  {
    id: "phone",
    name: "phone",
    label: "Phone Number",
    type: "tel",
    colSize: 6,
    can_be_disabled: false,
  },
  {
    id: "DOB",
    name: "Date of Birth",
    label: "Date of Birth",
    type: "date",
    colSize: 6,
  },
  {
    id: "fatherName",
    name: "Father name",
    label: "Father name",
    type: "text",
    colSize: 12,
    can_be_disabled: false,
  },
  {
    id: "fatherProfession",
    name: "Father’s profession",
    label: "Father’s profession",
    type: "text",
    colSize: 12,
    can_be_disabled: false,
  },
  {
    id: "motherName",
    name: "Mother name",
    label: "Mother name",
    type: "text",
    colSize: 12,
    can_be_disabled: false,
  },
  {
    id: "motherProfession",
    name: "Mother’s profession",
    label: "Mother’s profession",
    type: "text",
    colSize: 12,
    can_be_disabled: false,
  },
  {
    id: "caste",
    name: "Caste",
    label: "Caste",
    type: "text",
    colSize: 6,
    can_be_disabled: false,
  },
  {
    id: "religion",
    name: "Religion",
    label: "Religion",
    type: "text",
    colSize: 6,
    can_be_disabled: false,
  },
  {
    id: "currentClass",
    name: "Current class",
    label: "Current class",
    type: "number",
    colSize: 6,
    can_be_disabled: false,
  },
  {
    id: "Last class",
    name: "Last class",
    label: "Last class",
    type: "number",
    colSize: 6,
    can_be_disabled: false,
  },
  {
    id: "district",
    name: "District",
    label: "District",
    type: "text",
    colSize: 6,
    can_be_disabled: false,
  },
  {
    id: "block",
    name: "Block",
    label: "Block",
    type: "text",
    colSize: 6,
    can_be_disabled: false,
  },
  {
    id: "correspondingAddress",
    name: "Corresponding address",
    label: "Corresponding address",
    type: "text",
    colSize: 12,
    can_be_disabled: false,
  },
];
